version: '3'

services:
  ppanel-admin-web:
    image: ppanel/ppanel-admin-web:beta
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_SITE_URL: https://fo3.netfly.life
      NEXT_PUBLIC_API_URL: 16690850f19f4af0dd87d1b11d660a32
  ppanel-user-web:
    image: ppanel/ppanel-user-web:beta
    ports:
      - '3001:3000'
    environment:
      NEXT_PUBLIC_DEFAULT_LANGUAGE: zh-CN
      NEXT_PUBLIC_SITE_URL: https://fo3.netfly.life
      NEXT_PUBLIC_API_URL: https://api.netfly.life
      NEXT_PUBLIC_EMAIL: contact@example.com
      NEXT_PUBLIC_TELEGRAM_LINK: https://t.me/example
      NEXT_PUBLIC_TWITTER_LINK: https://twitter.com/example
      NEXT_PUBLIC_DISCORD_LINK: https://discord.com/example
      NEXT_PUBLIC_INSTAGRAM_LINK: https://instagram.com/example
      NEXT_PUBLIC_LINKEDIN_LINK: https://linkedin.com/example
      NEXT_PUBLIC_FACEBOOK_LINK: https://facebook.com/example
      NEXT_PUBLIC_GITHUB_LINK: https://github.com/example/repository
      NEXT_PUBLIC_DEFAULT_USER_EMAIL: user@example.com
      NEXT_PUBLIC_DEFAULT_USER_PASSWORD: password123
